# Generated by Django 4.2.3 on 2025-11-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_created_at_task_user_alter_task_dependencies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
