# Generated by Django 4.2.3 on 2025-11-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
