# Generated by Django 4.2.3 on 2025-11-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='feedback_helpful',
            field=models.BooleanField(default=False),
        ),
    ]
