# Generated by Django 4.2.3 on 2025-11-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_task_feedback_helpful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='feedback_helpful',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
